### PR TITLE
bind and unbind vao when drawing

### LINKED ISSUE #9: VAO needs to be unbound after a draw
It looks like the `vao` created for text, lines, and the background need to be unbound after drawing. It causes out of bound reads for subsequent draw calls in other frameworks such as https://github.com/littlstar/axis3d

I'll have a PR submitted shortly that addresses this!

### PR DESCRIPTION
**Pull request by jwerle**
cc @mikolalysenko @hughsk @dfcreative 
This fixes #9

### CODE REVIEW

**Comment by jwerle** [comment]
beep

**Comment by dfcreative** [comment]
Looks good, though we gotta make sure it does not cause warnings in plotly cases

**Comment by jwerle** [comment]
@dfcreative yeah absolutely. I just checked this module and it appears to work fine with `gl-plot3d`. however, you would probably know the modules to check to make sure there aren't any regressions :]

**Comment by dfcreative** [comment]
Superceded by #11. Thanks @jwerle!

**Pull request closed without merging**
